cloc /tmp/buggy_Chart_1/source --csv > loc/Chart_1.csv
cloc /tmp/buggy_Chart_10/source --csv > loc/Chart_10.csv
cloc /tmp/buggy_Chart_11/source --csv > loc/Chart_11.csv
cloc /tmp/buggy_Chart_12/source --csv > loc/Chart_12.csv
cloc /tmp/buggy_Chart_13/source --csv > loc/Chart_13.csv
cloc /tmp/buggy_Chart_14/source --csv > loc/Chart_14.csv
cloc /tmp/buggy_Chart_15/source --csv > loc/Chart_15.csv
cloc /tmp/buggy_Chart_17/source --csv > loc/Chart_17.csv
cloc /tmp/buggy_Chart_18/source --csv > loc/Chart_18.csv
cloc /tmp/buggy_Chart_19/source --csv > loc/Chart_19.csv
cloc /tmp/buggy_Chart_2/source --csv > loc/Chart_2.csv
cloc /tmp/buggy_Chart_20/source --csv > loc/Chart_20.csv
cloc /tmp/buggy_Chart_21/source --csv > loc/Chart_21.csv
cloc /tmp/buggy_Chart_22/source --csv > loc/Chart_22.csv
cloc /tmp/buggy_Chart_23/source --csv > loc/Chart_23.csv
cloc /tmp/buggy_Chart_24/source --csv > loc/Chart_24.csv
cloc /tmp/buggy_Chart_25/source --csv > loc/Chart_25.csv
cloc /tmp/buggy_Chart_26/source --csv > loc/Chart_26.csv
cloc /tmp/buggy_Chart_3/source --csv > loc/Chart_3.csv
cloc /tmp/buggy_Chart_4/source --csv > loc/Chart_4.csv
cloc /tmp/buggy_Chart_5/source --csv > loc/Chart_5.csv
cloc /tmp/buggy_Chart_6/source --csv > loc/Chart_6.csv
cloc /tmp/buggy_Chart_7/source --csv > loc/Chart_7.csv
cloc /tmp/buggy_Chart_8/source --csv > loc/Chart_8.csv
cloc /tmp/buggy_Chart_9/source --csv > loc/Chart_9.csv
cloc /tmp/buggy_Closure_1/src --csv > loc/Closure_1.csv
cloc /tmp/buggy_Closure_10/src --csv > loc/Closure_10.csv
cloc /tmp/buggy_Closure_100/src --csv > loc/Closure_100.csv
cloc /tmp/buggy_Closure_101/src --csv > loc/Closure_101.csv
cloc /tmp/buggy_Closure_102/src --csv > loc/Closure_102.csv
cloc /tmp/buggy_Closure_103/src --csv > loc/Closure_103.csv
cloc /tmp/buggy_Closure_104/src --csv > loc/Closure_104.csv
cloc /tmp/buggy_Closure_105/src --csv > loc/Closure_105.csv
cloc /tmp/buggy_Closure_106/src --csv > loc/Closure_106.csv
cloc /tmp/buggy_Closure_107/src --csv > loc/Closure_107.csv
cloc /tmp/buggy_Closure_108/src --csv > loc/Closure_108.csv
cloc /tmp/buggy_Closure_109/src --csv > loc/Closure_109.csv
cloc /tmp/buggy_Closure_11/src --csv > loc/Closure_11.csv
cloc /tmp/buggy_Closure_110/src --csv > loc/Closure_110.csv
cloc /tmp/buggy_Closure_112/src --csv > loc/Closure_112.csv
cloc /tmp/buggy_Closure_113/src --csv > loc/Closure_113.csv
cloc /tmp/buggy_Closure_114/src --csv > loc/Closure_114.csv
cloc /tmp/buggy_Closure_115/src --csv > loc/Closure_115.csv
cloc /tmp/buggy_Closure_116/src --csv > loc/Closure_116.csv
cloc /tmp/buggy_Closure_117/src --csv > loc/Closure_117.csv
cloc /tmp/buggy_Closure_118/src --csv > loc/Closure_118.csv
cloc /tmp/buggy_Closure_119/src --csv > loc/Closure_119.csv
cloc /tmp/buggy_Closure_12/src --csv > loc/Closure_12.csv
cloc /tmp/buggy_Closure_120/src --csv > loc/Closure_120.csv
cloc /tmp/buggy_Closure_121/src --csv > loc/Closure_121.csv
cloc /tmp/buggy_Closure_122/src --csv > loc/Closure_122.csv
cloc /tmp/buggy_Closure_123/src --csv > loc/Closure_123.csv
cloc /tmp/buggy_Closure_124/src --csv > loc/Closure_124.csv
cloc /tmp/buggy_Closure_125/src --csv > loc/Closure_125.csv
cloc /tmp/buggy_Closure_126/src --csv > loc/Closure_126.csv
cloc /tmp/buggy_Closure_127/src --csv > loc/Closure_127.csv
cloc /tmp/buggy_Closure_128/src --csv > loc/Closure_128.csv
cloc /tmp/buggy_Closure_129/src --csv > loc/Closure_129.csv
cloc /tmp/buggy_Closure_13/src --csv > loc/Closure_13.csv
cloc /tmp/buggy_Closure_130/src --csv > loc/Closure_130.csv
cloc /tmp/buggy_Closure_131/src --csv > loc/Closure_131.csv
cloc /tmp/buggy_Closure_132/src --csv > loc/Closure_132.csv
cloc /tmp/buggy_Closure_133/src --csv > loc/Closure_133.csv
cloc /tmp/buggy_Closure_14/src --csv > loc/Closure_14.csv
cloc /tmp/buggy_Closure_15/src --csv > loc/Closure_15.csv
cloc /tmp/buggy_Closure_16/src --csv > loc/Closure_16.csv
cloc /tmp/buggy_Closure_17/src --csv > loc/Closure_17.csv
cloc /tmp/buggy_Closure_18/src --csv > loc/Closure_18.csv
cloc /tmp/buggy_Closure_19/src --csv > loc/Closure_19.csv
cloc /tmp/buggy_Closure_2/src --csv > loc/Closure_2.csv
cloc /tmp/buggy_Closure_20/src --csv > loc/Closure_20.csv
cloc /tmp/buggy_Closure_21/src --csv > loc/Closure_21.csv
cloc /tmp/buggy_Closure_22/src --csv > loc/Closure_22.csv
cloc /tmp/buggy_Closure_23/src --csv > loc/Closure_23.csv
cloc /tmp/buggy_Closure_24/src --csv > loc/Closure_24.csv
cloc /tmp/buggy_Closure_25/src --csv > loc/Closure_25.csv
cloc /tmp/buggy_Closure_26/src --csv > loc/Closure_26.csv
cloc /tmp/buggy_Closure_27/src --csv > loc/Closure_27.csv
cloc /tmp/buggy_Closure_28/src --csv > loc/Closure_28.csv
cloc /tmp/buggy_Closure_29/src --csv > loc/Closure_29.csv
cloc /tmp/buggy_Closure_3/src --csv > loc/Closure_3.csv
cloc /tmp/buggy_Closure_30/src --csv > loc/Closure_30.csv
cloc /tmp/buggy_Closure_31/src --csv > loc/Closure_31.csv
cloc /tmp/buggy_Closure_32/src --csv > loc/Closure_32.csv
cloc /tmp/buggy_Closure_33/src --csv > loc/Closure_33.csv
cloc /tmp/buggy_Closure_34/src --csv > loc/Closure_34.csv
cloc /tmp/buggy_Closure_35/src --csv > loc/Closure_35.csv
cloc /tmp/buggy_Closure_36/src --csv > loc/Closure_36.csv
cloc /tmp/buggy_Closure_37/src --csv > loc/Closure_37.csv
cloc /tmp/buggy_Closure_38/src --csv > loc/Closure_38.csv
cloc /tmp/buggy_Closure_39/src --csv > loc/Closure_39.csv
cloc /tmp/buggy_Closure_4/src --csv > loc/Closure_4.csv
cloc /tmp/buggy_Closure_40/src --csv > loc/Closure_40.csv
cloc /tmp/buggy_Closure_41/src --csv > loc/Closure_41.csv
cloc /tmp/buggy_Closure_42/src --csv > loc/Closure_42.csv
cloc /tmp/buggy_Closure_43/src --csv > loc/Closure_43.csv
cloc /tmp/buggy_Closure_44/src --csv > loc/Closure_44.csv
cloc /tmp/buggy_Closure_45/src --csv > loc/Closure_45.csv
cloc /tmp/buggy_Closure_46/src --csv > loc/Closure_46.csv
cloc /tmp/buggy_Closure_47/src --csv > loc/Closure_47.csv
cloc /tmp/buggy_Closure_48/src --csv > loc/Closure_48.csv
cloc /tmp/buggy_Closure_49/src --csv > loc/Closure_49.csv
cloc /tmp/buggy_Closure_5/src --csv > loc/Closure_5.csv
cloc /tmp/buggy_Closure_50/src --csv > loc/Closure_50.csv
cloc /tmp/buggy_Closure_51/src --csv > loc/Closure_51.csv
cloc /tmp/buggy_Closure_52/src --csv > loc/Closure_52.csv
cloc /tmp/buggy_Closure_53/src --csv > loc/Closure_53.csv
cloc /tmp/buggy_Closure_54/src --csv > loc/Closure_54.csv
cloc /tmp/buggy_Closure_55/src --csv > loc/Closure_55.csv
cloc /tmp/buggy_Closure_56/src --csv > loc/Closure_56.csv
cloc /tmp/buggy_Closure_57/src --csv > loc/Closure_57.csv
cloc /tmp/buggy_Closure_58/src --csv > loc/Closure_58.csv
cloc /tmp/buggy_Closure_59/src --csv > loc/Closure_59.csv
cloc /tmp/buggy_Closure_6/src --csv > loc/Closure_6.csv
cloc /tmp/buggy_Closure_60/src --csv > loc/Closure_60.csv
cloc /tmp/buggy_Closure_61/src --csv > loc/Closure_61.csv
cloc /tmp/buggy_Closure_62/src --csv > loc/Closure_62.csv
cloc /tmp/buggy_Closure_64/src --csv > loc/Closure_64.csv
cloc /tmp/buggy_Closure_65/src --csv > loc/Closure_65.csv
cloc /tmp/buggy_Closure_66/src --csv > loc/Closure_66.csv
cloc /tmp/buggy_Closure_67/src --csv > loc/Closure_67.csv
cloc /tmp/buggy_Closure_68/src --csv > loc/Closure_68.csv
cloc /tmp/buggy_Closure_69/src --csv > loc/Closure_69.csv
cloc /tmp/buggy_Closure_7/src --csv > loc/Closure_7.csv
cloc /tmp/buggy_Closure_70/src --csv > loc/Closure_70.csv
cloc /tmp/buggy_Closure_71/src --csv > loc/Closure_71.csv
cloc /tmp/buggy_Closure_72/src --csv > loc/Closure_72.csv
cloc /tmp/buggy_Closure_73/src --csv > loc/Closure_73.csv
cloc /tmp/buggy_Closure_74/src --csv > loc/Closure_74.csv
cloc /tmp/buggy_Closure_75/src --csv > loc/Closure_75.csv
cloc /tmp/buggy_Closure_76/src --csv > loc/Closure_76.csv
cloc /tmp/buggy_Closure_77/src --csv > loc/Closure_77.csv
cloc /tmp/buggy_Closure_78/src --csv > loc/Closure_78.csv
cloc /tmp/buggy_Closure_79/src --csv > loc/Closure_79.csv
cloc /tmp/buggy_Closure_8/src --csv > loc/Closure_8.csv
cloc /tmp/buggy_Closure_80/src --csv > loc/Closure_80.csv
cloc /tmp/buggy_Closure_81/src --csv > loc/Closure_81.csv
cloc /tmp/buggy_Closure_82/src --csv > loc/Closure_82.csv
cloc /tmp/buggy_Closure_83/src --csv > loc/Closure_83.csv
cloc /tmp/buggy_Closure_84/src --csv > loc/Closure_84.csv
cloc /tmp/buggy_Closure_85/src --csv > loc/Closure_85.csv
cloc /tmp/buggy_Closure_86/src --csv > loc/Closure_86.csv
cloc /tmp/buggy_Closure_87/src --csv > loc/Closure_87.csv
cloc /tmp/buggy_Closure_88/src --csv > loc/Closure_88.csv
cloc /tmp/buggy_Closure_89/src --csv > loc/Closure_89.csv
cloc /tmp/buggy_Closure_9/src --csv > loc/Closure_9.csv
cloc /tmp/buggy_Closure_90/src --csv > loc/Closure_90.csv
cloc /tmp/buggy_Closure_91/src --csv > loc/Closure_91.csv
cloc /tmp/buggy_Closure_92/src --csv > loc/Closure_92.csv
cloc /tmp/buggy_Closure_94/src --csv > loc/Closure_94.csv
cloc /tmp/buggy_Closure_95/src --csv > loc/Closure_95.csv
cloc /tmp/buggy_Closure_96/src --csv > loc/Closure_96.csv
cloc /tmp/buggy_Closure_97/src --csv > loc/Closure_97.csv
cloc /tmp/buggy_Closure_98/src --csv > loc/Closure_98.csv
cloc /tmp/buggy_Closure_99/src --csv > loc/Closure_99.csv
cloc /tmp/buggy_Lang_1/src/main/java --csv > loc/Lang_1.csv
cloc /tmp/buggy_Lang_10/src/main/java --csv > loc/Lang_10.csv
cloc /tmp/buggy_Lang_11/src/main/java --csv > loc/Lang_11.csv
cloc /tmp/buggy_Lang_12/src/main/java --csv > loc/Lang_12.csv
cloc /tmp/buggy_Lang_13/src/main/java --csv > loc/Lang_13.csv
cloc /tmp/buggy_Lang_14/src/main/java --csv > loc/Lang_14.csv
cloc /tmp/buggy_Lang_15/src/main/java --csv > loc/Lang_15.csv
cloc /tmp/buggy_Lang_16/src/main/java --csv > loc/Lang_16.csv
cloc /tmp/buggy_Lang_17/src/main/java --csv > loc/Lang_17.csv
cloc /tmp/buggy_Lang_19/src/main/java --csv > loc/Lang_19.csv
cloc /tmp/buggy_Lang_20/src/main/java --csv > loc/Lang_20.csv
cloc /tmp/buggy_Lang_21/src/main/java --csv > loc/Lang_21.csv
cloc /tmp/buggy_Lang_22/src/main/java --csv > loc/Lang_22.csv
cloc /tmp/buggy_Lang_23/src/main/java --csv > loc/Lang_23.csv
cloc /tmp/buggy_Lang_24/src/main/java --csv > loc/Lang_24.csv
cloc /tmp/buggy_Lang_26/src/main/java --csv > loc/Lang_26.csv
cloc /tmp/buggy_Lang_27/src/main/java --csv > loc/Lang_27.csv
cloc /tmp/buggy_Lang_28/src/main/java --csv > loc/Lang_28.csv
cloc /tmp/buggy_Lang_29/src/main/java --csv > loc/Lang_29.csv
cloc /tmp/buggy_Lang_3/src/main/java --csv > loc/Lang_3.csv
cloc /tmp/buggy_Lang_30/src/main/java --csv > loc/Lang_30.csv
cloc /tmp/buggy_Lang_31/src/main/java --csv > loc/Lang_31.csv
cloc /tmp/buggy_Lang_32/src/main/java --csv > loc/Lang_32.csv
cloc /tmp/buggy_Lang_33/src/main/java --csv > loc/Lang_33.csv
cloc /tmp/buggy_Lang_34/src/main/java --csv > loc/Lang_34.csv
cloc /tmp/buggy_Lang_35/src/main/java --csv > loc/Lang_35.csv
cloc /tmp/buggy_Lang_36/src/java --csv > loc/Lang_36.csv
cloc /tmp/buggy_Lang_37/src/java --csv > loc/Lang_37.csv
cloc /tmp/buggy_Lang_38/src/java --csv > loc/Lang_38.csv
cloc /tmp/buggy_Lang_39/src/java --csv > loc/Lang_39.csv
cloc /tmp/buggy_Lang_4/src/main/java --csv > loc/Lang_4.csv
cloc /tmp/buggy_Lang_40/src/java --csv > loc/Lang_40.csv
cloc /tmp/buggy_Lang_41/src/java --csv > loc/Lang_41.csv
cloc /tmp/buggy_Lang_42/src/java --csv > loc/Lang_42.csv
cloc /tmp/buggy_Lang_43/src/java --csv > loc/Lang_43.csv
cloc /tmp/buggy_Lang_44/src/java --csv > loc/Lang_44.csv
cloc /tmp/buggy_Lang_45/src/java --csv > loc/Lang_45.csv
cloc /tmp/buggy_Lang_46/src/java --csv > loc/Lang_46.csv
cloc /tmp/buggy_Lang_47/src/java --csv > loc/Lang_47.csv
cloc /tmp/buggy_Lang_49/src/java --csv > loc/Lang_49.csv
cloc /tmp/buggy_Lang_5/src/main/java --csv > loc/Lang_5.csv
cloc /tmp/buggy_Lang_50/src/java --csv > loc/Lang_50.csv
cloc /tmp/buggy_Lang_51/src/java --csv > loc/Lang_51.csv
cloc /tmp/buggy_Lang_52/src/java --csv > loc/Lang_52.csv
cloc /tmp/buggy_Lang_53/src/java --csv > loc/Lang_53.csv
cloc /tmp/buggy_Lang_54/src/java --csv > loc/Lang_54.csv
cloc /tmp/buggy_Lang_55/src/java --csv > loc/Lang_55.csv
cloc /tmp/buggy_Lang_56/src/java --csv > loc/Lang_56.csv
cloc /tmp/buggy_Lang_57/src/java --csv > loc/Lang_57.csv
cloc /tmp/buggy_Lang_58/src/java --csv > loc/Lang_58.csv
cloc /tmp/buggy_Lang_59/src/java --csv > loc/Lang_59.csv
cloc /tmp/buggy_Lang_6/src/main/java --csv > loc/Lang_6.csv
cloc /tmp/buggy_Lang_60/src/java --csv > loc/Lang_60.csv
cloc /tmp/buggy_Lang_61/src/java --csv > loc/Lang_61.csv
cloc /tmp/buggy_Lang_62/src/java --csv > loc/Lang_62.csv
cloc /tmp/buggy_Lang_63/src/java --csv > loc/Lang_63.csv
cloc /tmp/buggy_Lang_64/src/java --csv > loc/Lang_64.csv
cloc /tmp/buggy_Lang_65/src/java --csv > loc/Lang_65.csv
cloc /tmp/buggy_Lang_7/src/main/java --csv > loc/Lang_7.csv
cloc /tmp/buggy_Lang_8/src/main/java --csv > loc/Lang_8.csv
cloc /tmp/buggy_Lang_9/src/main/java --csv > loc/Lang_9.csv
cloc /tmp/buggy_Math_1/src/main/java --csv > loc/Math_1.csv
cloc /tmp/buggy_Math_10/src/main/java --csv > loc/Math_10.csv
cloc /tmp/buggy_Math_100/src/java --csv > loc/Math_100.csv
cloc /tmp/buggy_Math_101/src/java --csv > loc/Math_101.csv
cloc /tmp/buggy_Math_102/src/java --csv > loc/Math_102.csv
cloc /tmp/buggy_Math_103/src/java --csv > loc/Math_103.csv
cloc /tmp/buggy_Math_104/src/java --csv > loc/Math_104.csv
cloc /tmp/buggy_Math_105/src/java --csv > loc/Math_105.csv
cloc /tmp/buggy_Math_106/src/java --csv > loc/Math_106.csv
cloc /tmp/buggy_Math_11/src/main/java --csv > loc/Math_11.csv
cloc /tmp/buggy_Math_12/src/main/java --csv > loc/Math_12.csv
cloc /tmp/buggy_Math_13/src/main/java --csv > loc/Math_13.csv
cloc /tmp/buggy_Math_14/src/main/java --csv > loc/Math_14.csv
cloc /tmp/buggy_Math_15/src/main/java --csv > loc/Math_15.csv
cloc /tmp/buggy_Math_16/src/main/java --csv > loc/Math_16.csv
cloc /tmp/buggy_Math_17/src/main/java --csv > loc/Math_17.csv
cloc /tmp/buggy_Math_18/src/main/java --csv > loc/Math_18.csv
cloc /tmp/buggy_Math_19/src/main/java --csv > loc/Math_19.csv
cloc /tmp/buggy_Math_2/src/main/java --csv > loc/Math_2.csv
cloc /tmp/buggy_Math_20/src/main/java --csv > loc/Math_20.csv
cloc /tmp/buggy_Math_21/src/main/java --csv > loc/Math_21.csv
cloc /tmp/buggy_Math_22/src/main/java --csv > loc/Math_22.csv
cloc /tmp/buggy_Math_23/src/main/java --csv > loc/Math_23.csv
cloc /tmp/buggy_Math_24/src/main/java --csv > loc/Math_24.csv
cloc /tmp/buggy_Math_25/src/main/java --csv > loc/Math_25.csv
cloc /tmp/buggy_Math_26/src/main/java --csv > loc/Math_26.csv
cloc /tmp/buggy_Math_27/src/main/java --csv > loc/Math_27.csv
cloc /tmp/buggy_Math_28/src/main/java --csv > loc/Math_28.csv
cloc /tmp/buggy_Math_29/src/main/java --csv > loc/Math_29.csv
cloc /tmp/buggy_Math_3/src/main/java --csv > loc/Math_3.csv
cloc /tmp/buggy_Math_30/src/main/java --csv > loc/Math_30.csv
cloc /tmp/buggy_Math_31/src/main/java --csv > loc/Math_31.csv
cloc /tmp/buggy_Math_32/src/main/java --csv > loc/Math_32.csv
cloc /tmp/buggy_Math_33/src/main/java --csv > loc/Math_33.csv
cloc /tmp/buggy_Math_34/src/main/java --csv > loc/Math_34.csv
cloc /tmp/buggy_Math_35/src/main/java --csv > loc/Math_35.csv
cloc /tmp/buggy_Math_36/src/main/java --csv > loc/Math_36.csv
cloc /tmp/buggy_Math_37/src/main/java --csv > loc/Math_37.csv
cloc /tmp/buggy_Math_38/src/main/java --csv > loc/Math_38.csv
cloc /tmp/buggy_Math_39/src/main/java --csv > loc/Math_39.csv
cloc /tmp/buggy_Math_4/src/main/java --csv > loc/Math_4.csv
cloc /tmp/buggy_Math_40/src/main/java --csv > loc/Math_40.csv
cloc /tmp/buggy_Math_41/src/main/java --csv > loc/Math_41.csv
cloc /tmp/buggy_Math_42/src/main/java --csv > loc/Math_42.csv
cloc /tmp/buggy_Math_43/src/main/java --csv > loc/Math_43.csv
cloc /tmp/buggy_Math_44/src/main/java --csv > loc/Math_44.csv
cloc /tmp/buggy_Math_45/src/main/java --csv > loc/Math_45.csv
cloc /tmp/buggy_Math_46/src/main/java --csv > loc/Math_46.csv
cloc /tmp/buggy_Math_47/src/main/java --csv > loc/Math_47.csv
cloc /tmp/buggy_Math_48/src/main/java --csv > loc/Math_48.csv
cloc /tmp/buggy_Math_49/src/main/java --csv > loc/Math_49.csv
cloc /tmp/buggy_Math_5/src/main/java --csv > loc/Math_5.csv
cloc /tmp/buggy_Math_50/src/main/java --csv > loc/Math_50.csv
cloc /tmp/buggy_Math_51/src/main/java --csv > loc/Math_51.csv
cloc /tmp/buggy_Math_52/src/main/java --csv > loc/Math_52.csv
cloc /tmp/buggy_Math_53/src/main/java --csv > loc/Math_53.csv
cloc /tmp/buggy_Math_54/src/main/java --csv > loc/Math_54.csv
cloc /tmp/buggy_Math_55/src/main/java --csv > loc/Math_55.csv
cloc /tmp/buggy_Math_56/src/main/java --csv > loc/Math_56.csv
cloc /tmp/buggy_Math_57/src/main/java --csv > loc/Math_57.csv
cloc /tmp/buggy_Math_58/src/main/java --csv > loc/Math_58.csv
cloc /tmp/buggy_Math_59/src/main/java --csv > loc/Math_59.csv
cloc /tmp/buggy_Math_6/src/main/java --csv > loc/Math_6.csv
cloc /tmp/buggy_Math_60/src/main/java --csv > loc/Math_60.csv
cloc /tmp/buggy_Math_61/src/main/java --csv > loc/Math_61.csv
cloc /tmp/buggy_Math_62/src/main/java --csv > loc/Math_62.csv
cloc /tmp/buggy_Math_63/src/main/java --csv > loc/Math_63.csv
cloc /tmp/buggy_Math_64/src/main/java --csv > loc/Math_64.csv
cloc /tmp/buggy_Math_65/src/main/java --csv > loc/Math_65.csv
cloc /tmp/buggy_Math_66/src/main/java --csv > loc/Math_66.csv
cloc /tmp/buggy_Math_67/src/main/java --csv > loc/Math_67.csv
cloc /tmp/buggy_Math_68/src/main/java --csv > loc/Math_68.csv
cloc /tmp/buggy_Math_69/src/main/java --csv > loc/Math_69.csv
cloc /tmp/buggy_Math_7/src/main/java --csv > loc/Math_7.csv
cloc /tmp/buggy_Math_70/src/main/java --csv > loc/Math_70.csv
cloc /tmp/buggy_Math_71/src/main/java --csv > loc/Math_71.csv
cloc /tmp/buggy_Math_72/src/main/java --csv > loc/Math_72.csv
cloc /tmp/buggy_Math_73/src/main/java --csv > loc/Math_73.csv
cloc /tmp/buggy_Math_74/src/main/java --csv > loc/Math_74.csv
cloc /tmp/buggy_Math_75/src/main/java --csv > loc/Math_75.csv
cloc /tmp/buggy_Math_76/src/main/java --csv > loc/Math_76.csv
cloc /tmp/buggy_Math_77/src/main/java --csv > loc/Math_77.csv
cloc /tmp/buggy_Math_78/src/main/java --csv > loc/Math_78.csv
cloc /tmp/buggy_Math_79/src/main/java --csv > loc/Math_79.csv
cloc /tmp/buggy_Math_8/src/main/java --csv > loc/Math_8.csv
cloc /tmp/buggy_Math_80/src/main/java --csv > loc/Math_80.csv
cloc /tmp/buggy_Math_81/src/main/java --csv > loc/Math_81.csv
cloc /tmp/buggy_Math_82/src/main/java --csv > loc/Math_82.csv
cloc /tmp/buggy_Math_83/src/main/java --csv > loc/Math_83.csv
cloc /tmp/buggy_Math_84/src/main/java --csv > loc/Math_84.csv
cloc /tmp/buggy_Math_85/src/java --csv > loc/Math_85.csv
cloc /tmp/buggy_Math_86/src/java --csv > loc/Math_86.csv
cloc /tmp/buggy_Math_87/src/java --csv > loc/Math_87.csv
cloc /tmp/buggy_Math_88/src/java --csv > loc/Math_88.csv
cloc /tmp/buggy_Math_89/src/java --csv > loc/Math_89.csv
cloc /tmp/buggy_Math_9/src/main/java --csv > loc/Math_9.csv
cloc /tmp/buggy_Math_90/src/java --csv > loc/Math_90.csv
cloc /tmp/buggy_Math_91/src/java --csv > loc/Math_91.csv
cloc /tmp/buggy_Math_92/src/java --csv > loc/Math_92.csv
cloc /tmp/buggy_Math_93/src/java --csv > loc/Math_93.csv
cloc /tmp/buggy_Math_94/src/java --csv > loc/Math_94.csv
cloc /tmp/buggy_Math_95/src/java --csv > loc/Math_95.csv
cloc /tmp/buggy_Math_96/src/java --csv > loc/Math_96.csv
cloc /tmp/buggy_Math_97/src/java --csv > loc/Math_97.csv
cloc /tmp/buggy_Math_98/src/java --csv > loc/Math_98.csv
cloc /tmp/buggy_Math_99/src/java --csv > loc/Math_99.csv
cloc /tmp/buggy_Time_1/src/main/java --csv > loc/Time_1.csv
cloc /tmp/buggy_Time_10/src/main/java --csv > loc/Time_10.csv
cloc /tmp/buggy_Time_11/src/main/java --csv > loc/Time_11.csv
cloc /tmp/buggy_Time_12/src/main/java --csv > loc/Time_12.csv
cloc /tmp/buggy_Time_13/src/main/java --csv > loc/Time_13.csv
cloc /tmp/buggy_Time_14/src/main/java --csv > loc/Time_14.csv
cloc /tmp/buggy_Time_15/src/main/java --csv > loc/Time_15.csv
cloc /tmp/buggy_Time_16/src/main/java --csv > loc/Time_16.csv
cloc /tmp/buggy_Time_17/src/main/java --csv > loc/Time_17.csv
cloc /tmp/buggy_Time_18/src/main/java --csv > loc/Time_18.csv
cloc /tmp/buggy_Time_19/src/main/java --csv > loc/Time_19.csv
cloc /tmp/buggy_Time_2/src/main/java --csv > loc/Time_2.csv
cloc /tmp/buggy_Time_20/src/main/java --csv > loc/Time_20.csv
cloc /tmp/buggy_Time_22/src/main/java --csv > loc/Time_22.csv
cloc /tmp/buggy_Time_23/src/main/java --csv > loc/Time_23.csv
cloc /tmp/buggy_Time_24/src/main/java --csv > loc/Time_24.csv
cloc /tmp/buggy_Time_25/src/main/java --csv > loc/Time_25.csv
cloc /tmp/buggy_Time_26/src/main/java --csv > loc/Time_26.csv
cloc /tmp/buggy_Time_27/src/main/java --csv > loc/Time_27.csv
cloc /tmp/buggy_Time_3/src/main/java --csv > loc/Time_3.csv
cloc /tmp/buggy_Time_4/src/main/java --csv > loc/Time_4.csv
cloc /tmp/buggy_Time_5/src/main/java --csv > loc/Time_5.csv
cloc /tmp/buggy_Time_6/src/main/java --csv > loc/Time_6.csv
cloc /tmp/buggy_Time_7/src/main/java --csv > loc/Time_7.csv
cloc /tmp/buggy_Time_8/src/main/java --csv > loc/Time_8.csv
cloc /tmp/buggy_Time_9/src/main/java --csv > loc/Time_9.csv
