python3 count_methods.py /tmp/buggy_Chart_1/source -o methods/Chart_1.txt
python3 count_methods.py /tmp/buggy_Chart_10/source -o methods/Chart_10.txt
python3 count_methods.py /tmp/buggy_Chart_11/source -o methods/Chart_11.txt
python3 count_methods.py /tmp/buggy_Chart_12/source -o methods/Chart_12.txt
python3 count_methods.py /tmp/buggy_Chart_13/source -o methods/Chart_13.txt
python3 count_methods.py /tmp/buggy_Chart_14/source -o methods/Chart_14.txt
python3 count_methods.py /tmp/buggy_Chart_15/source -o methods/Chart_15.txt
python3 count_methods.py /tmp/buggy_Chart_16/source -o methods/Chart_16.txt
python3 count_methods.py /tmp/buggy_Chart_17/source -o methods/Chart_17.txt
python3 count_methods.py /tmp/buggy_Chart_18/source -o methods/Chart_18.txt
python3 count_methods.py /tmp/buggy_Chart_19/source -o methods/Chart_19.txt
python3 count_methods.py /tmp/buggy_Chart_2/source -o methods/Chart_2.txt
python3 count_methods.py /tmp/buggy_Chart_20/source -o methods/Chart_20.txt
python3 count_methods.py /tmp/buggy_Chart_21/source -o methods/Chart_21.txt
python3 count_methods.py /tmp/buggy_Chart_22/source -o methods/Chart_22.txt
python3 count_methods.py /tmp/buggy_Chart_23/source -o methods/Chart_23.txt
python3 count_methods.py /tmp/buggy_Chart_24/source -o methods/Chart_24.txt
python3 count_methods.py /tmp/buggy_Chart_25/source -o methods/Chart_25.txt
python3 count_methods.py /tmp/buggy_Chart_26/source -o methods/Chart_26.txt
python3 count_methods.py /tmp/buggy_Chart_3/source -o methods/Chart_3.txt
python3 count_methods.py /tmp/buggy_Chart_4/source -o methods/Chart_4.txt
python3 count_methods.py /tmp/buggy_Chart_5/source -o methods/Chart_5.txt
python3 count_methods.py /tmp/buggy_Chart_6/source -o methods/Chart_6.txt
python3 count_methods.py /tmp/buggy_Chart_7/source -o methods/Chart_7.txt
python3 count_methods.py /tmp/buggy_Chart_8/source -o methods/Chart_8.txt
python3 count_methods.py /tmp/buggy_Chart_9/source -o methods/Chart_9.txt
python3 count_methods.py /tmp/buggy_Closure_1/src -o methods/Closure_1.txt
python3 count_methods.py /tmp/buggy_Closure_10/src -o methods/Closure_10.txt
python3 count_methods.py /tmp/buggy_Closure_100/src -o methods/Closure_100.txt
python3 count_methods.py /tmp/buggy_Closure_101/src -o methods/Closure_101.txt
python3 count_methods.py /tmp/buggy_Closure_102/src -o methods/Closure_102.txt
python3 count_methods.py /tmp/buggy_Closure_103/src -o methods/Closure_103.txt
python3 count_methods.py /tmp/buggy_Closure_104/src -o methods/Closure_104.txt
python3 count_methods.py /tmp/buggy_Closure_105/src -o methods/Closure_105.txt
python3 count_methods.py /tmp/buggy_Closure_106/src -o methods/Closure_106.txt
python3 count_methods.py /tmp/buggy_Closure_107/src -o methods/Closure_107.txt
python3 count_methods.py /tmp/buggy_Closure_108/src -o methods/Closure_108.txt
python3 count_methods.py /tmp/buggy_Closure_109/src -o methods/Closure_109.txt
python3 count_methods.py /tmp/buggy_Closure_11/src -o methods/Closure_11.txt
python3 count_methods.py /tmp/buggy_Closure_110/src -o methods/Closure_110.txt
python3 count_methods.py /tmp/buggy_Closure_111/src -o methods/Closure_111.txt
python3 count_methods.py /tmp/buggy_Closure_112/src -o methods/Closure_112.txt
python3 count_methods.py /tmp/buggy_Closure_113/src -o methods/Closure_113.txt
python3 count_methods.py /tmp/buggy_Closure_114/src -o methods/Closure_114.txt
python3 count_methods.py /tmp/buggy_Closure_115/src -o methods/Closure_115.txt
python3 count_methods.py /tmp/buggy_Closure_116/src -o methods/Closure_116.txt
python3 count_methods.py /tmp/buggy_Closure_117/src -o methods/Closure_117.txt
python3 count_methods.py /tmp/buggy_Closure_118/src -o methods/Closure_118.txt
python3 count_methods.py /tmp/buggy_Closure_119/src -o methods/Closure_119.txt
python3 count_methods.py /tmp/buggy_Closure_12/src -o methods/Closure_12.txt
python3 count_methods.py /tmp/buggy_Closure_120/src -o methods/Closure_120.txt
python3 count_methods.py /tmp/buggy_Closure_121/src -o methods/Closure_121.txt
python3 count_methods.py /tmp/buggy_Closure_122/src -o methods/Closure_122.txt
python3 count_methods.py /tmp/buggy_Closure_123/src -o methods/Closure_123.txt
python3 count_methods.py /tmp/buggy_Closure_124/src -o methods/Closure_124.txt
python3 count_methods.py /tmp/buggy_Closure_125/src -o methods/Closure_125.txt
python3 count_methods.py /tmp/buggy_Closure_126/src -o methods/Closure_126.txt
python3 count_methods.py /tmp/buggy_Closure_127/src -o methods/Closure_127.txt
python3 count_methods.py /tmp/buggy_Closure_128/src -o methods/Closure_128.txt
python3 count_methods.py /tmp/buggy_Closure_129/src -o methods/Closure_129.txt
python3 count_methods.py /tmp/buggy_Closure_13/src -o methods/Closure_13.txt
python3 count_methods.py /tmp/buggy_Closure_130/src -o methods/Closure_130.txt
python3 count_methods.py /tmp/buggy_Closure_131/src -o methods/Closure_131.txt
python3 count_methods.py /tmp/buggy_Closure_132/src -o methods/Closure_132.txt
python3 count_methods.py /tmp/buggy_Closure_133/src -o methods/Closure_133.txt
python3 count_methods.py /tmp/buggy_Closure_14/src -o methods/Closure_14.txt
python3 count_methods.py /tmp/buggy_Closure_15/src -o methods/Closure_15.txt
python3 count_methods.py /tmp/buggy_Closure_16/src -o methods/Closure_16.txt
python3 count_methods.py /tmp/buggy_Closure_17/src -o methods/Closure_17.txt
python3 count_methods.py /tmp/buggy_Closure_18/src -o methods/Closure_18.txt
python3 count_methods.py /tmp/buggy_Closure_19/src -o methods/Closure_19.txt
python3 count_methods.py /tmp/buggy_Closure_2/src -o methods/Closure_2.txt
python3 count_methods.py /tmp/buggy_Closure_20/src -o methods/Closure_20.txt
python3 count_methods.py /tmp/buggy_Closure_21/src -o methods/Closure_21.txt
python3 count_methods.py /tmp/buggy_Closure_22/src -o methods/Closure_22.txt
python3 count_methods.py /tmp/buggy_Closure_23/src -o methods/Closure_23.txt
python3 count_methods.py /tmp/buggy_Closure_24/src -o methods/Closure_24.txt
python3 count_methods.py /tmp/buggy_Closure_25/src -o methods/Closure_25.txt
python3 count_methods.py /tmp/buggy_Closure_26/src -o methods/Closure_26.txt
python3 count_methods.py /tmp/buggy_Closure_27/src -o methods/Closure_27.txt
python3 count_methods.py /tmp/buggy_Closure_28/src -o methods/Closure_28.txt
python3 count_methods.py /tmp/buggy_Closure_29/src -o methods/Closure_29.txt
python3 count_methods.py /tmp/buggy_Closure_3/src -o methods/Closure_3.txt
python3 count_methods.py /tmp/buggy_Closure_30/src -o methods/Closure_30.txt
python3 count_methods.py /tmp/buggy_Closure_31/src -o methods/Closure_31.txt
python3 count_methods.py /tmp/buggy_Closure_32/src -o methods/Closure_32.txt
python3 count_methods.py /tmp/buggy_Closure_33/src -o methods/Closure_33.txt
python3 count_methods.py /tmp/buggy_Closure_34/src -o methods/Closure_34.txt
python3 count_methods.py /tmp/buggy_Closure_35/src -o methods/Closure_35.txt
python3 count_methods.py /tmp/buggy_Closure_36/src -o methods/Closure_36.txt
python3 count_methods.py /tmp/buggy_Closure_37/src -o methods/Closure_37.txt
python3 count_methods.py /tmp/buggy_Closure_38/src -o methods/Closure_38.txt
python3 count_methods.py /tmp/buggy_Closure_39/src -o methods/Closure_39.txt
python3 count_methods.py /tmp/buggy_Closure_4/src -o methods/Closure_4.txt
python3 count_methods.py /tmp/buggy_Closure_40/src -o methods/Closure_40.txt
python3 count_methods.py /tmp/buggy_Closure_41/src -o methods/Closure_41.txt
python3 count_methods.py /tmp/buggy_Closure_42/src -o methods/Closure_42.txt
python3 count_methods.py /tmp/buggy_Closure_43/src -o methods/Closure_43.txt
python3 count_methods.py /tmp/buggy_Closure_44/src -o methods/Closure_44.txt
python3 count_methods.py /tmp/buggy_Closure_45/src -o methods/Closure_45.txt
python3 count_methods.py /tmp/buggy_Closure_46/src -o methods/Closure_46.txt
python3 count_methods.py /tmp/buggy_Closure_47/src -o methods/Closure_47.txt
python3 count_methods.py /tmp/buggy_Closure_48/src -o methods/Closure_48.txt
python3 count_methods.py /tmp/buggy_Closure_49/src -o methods/Closure_49.txt
python3 count_methods.py /tmp/buggy_Closure_5/src -o methods/Closure_5.txt
python3 count_methods.py /tmp/buggy_Closure_50/src -o methods/Closure_50.txt
python3 count_methods.py /tmp/buggy_Closure_51/src -o methods/Closure_51.txt
python3 count_methods.py /tmp/buggy_Closure_52/src -o methods/Closure_52.txt
python3 count_methods.py /tmp/buggy_Closure_53/src -o methods/Closure_53.txt
python3 count_methods.py /tmp/buggy_Closure_54/src -o methods/Closure_54.txt
python3 count_methods.py /tmp/buggy_Closure_55/src -o methods/Closure_55.txt
python3 count_methods.py /tmp/buggy_Closure_56/src -o methods/Closure_56.txt
python3 count_methods.py /tmp/buggy_Closure_57/src -o methods/Closure_57.txt
python3 count_methods.py /tmp/buggy_Closure_58/src -o methods/Closure_58.txt
python3 count_methods.py /tmp/buggy_Closure_59/src -o methods/Closure_59.txt
python3 count_methods.py /tmp/buggy_Closure_6/src -o methods/Closure_6.txt
python3 count_methods.py /tmp/buggy_Closure_60/src -o methods/Closure_60.txt
python3 count_methods.py /tmp/buggy_Closure_61/src -o methods/Closure_61.txt
python3 count_methods.py /tmp/buggy_Closure_62/src -o methods/Closure_62.txt
python3 count_methods.py /tmp/buggy_Closure_64/src -o methods/Closure_64.txt
python3 count_methods.py /tmp/buggy_Closure_65/src -o methods/Closure_65.txt
python3 count_methods.py /tmp/buggy_Closure_66/src -o methods/Closure_66.txt
python3 count_methods.py /tmp/buggy_Closure_67/src -o methods/Closure_67.txt
python3 count_methods.py /tmp/buggy_Closure_68/src -o methods/Closure_68.txt
python3 count_methods.py /tmp/buggy_Closure_69/src -o methods/Closure_69.txt
python3 count_methods.py /tmp/buggy_Closure_7/src -o methods/Closure_7.txt
python3 count_methods.py /tmp/buggy_Closure_70/src -o methods/Closure_70.txt
python3 count_methods.py /tmp/buggy_Closure_71/src -o methods/Closure_71.txt
python3 count_methods.py /tmp/buggy_Closure_72/src -o methods/Closure_72.txt
python3 count_methods.py /tmp/buggy_Closure_73/src -o methods/Closure_73.txt
python3 count_methods.py /tmp/buggy_Closure_74/src -o methods/Closure_74.txt
python3 count_methods.py /tmp/buggy_Closure_75/src -o methods/Closure_75.txt
python3 count_methods.py /tmp/buggy_Closure_76/src -o methods/Closure_76.txt
python3 count_methods.py /tmp/buggy_Closure_77/src -o methods/Closure_77.txt
python3 count_methods.py /tmp/buggy_Closure_78/src -o methods/Closure_78.txt
python3 count_methods.py /tmp/buggy_Closure_79/src -o methods/Closure_79.txt
python3 count_methods.py /tmp/buggy_Closure_8/src -o methods/Closure_8.txt
python3 count_methods.py /tmp/buggy_Closure_80/src -o methods/Closure_80.txt
python3 count_methods.py /tmp/buggy_Closure_81/src -o methods/Closure_81.txt
python3 count_methods.py /tmp/buggy_Closure_82/src -o methods/Closure_82.txt
python3 count_methods.py /tmp/buggy_Closure_83/src -o methods/Closure_83.txt
python3 count_methods.py /tmp/buggy_Closure_84/src -o methods/Closure_84.txt
python3 count_methods.py /tmp/buggy_Closure_85/src -o methods/Closure_85.txt
python3 count_methods.py /tmp/buggy_Closure_86/src -o methods/Closure_86.txt
python3 count_methods.py /tmp/buggy_Closure_87/src -o methods/Closure_87.txt
python3 count_methods.py /tmp/buggy_Closure_88/src -o methods/Closure_88.txt
python3 count_methods.py /tmp/buggy_Closure_89/src -o methods/Closure_89.txt
python3 count_methods.py /tmp/buggy_Closure_9/src -o methods/Closure_9.txt
python3 count_methods.py /tmp/buggy_Closure_90/src -o methods/Closure_90.txt
python3 count_methods.py /tmp/buggy_Closure_91/src -o methods/Closure_91.txt
python3 count_methods.py /tmp/buggy_Closure_92/src -o methods/Closure_92.txt
python3 count_methods.py /tmp/buggy_Closure_94/src -o methods/Closure_94.txt
python3 count_methods.py /tmp/buggy_Closure_95/src -o methods/Closure_95.txt
python3 count_methods.py /tmp/buggy_Closure_96/src -o methods/Closure_96.txt
python3 count_methods.py /tmp/buggy_Closure_97/src -o methods/Closure_97.txt
python3 count_methods.py /tmp/buggy_Closure_98/src -o methods/Closure_98.txt
python3 count_methods.py /tmp/buggy_Closure_99/src -o methods/Closure_99.txt
python3 count_methods.py /tmp/buggy_Lang_1/src/main -o methods/Lang_1.txt
python3 count_methods.py /tmp/buggy_Lang_10/src/main -o methods/Lang_10.txt
python3 count_methods.py /tmp/buggy_Lang_11/src/main -o methods/Lang_11.txt
python3 count_methods.py /tmp/buggy_Lang_12/src/main -o methods/Lang_12.txt
python3 count_methods.py /tmp/buggy_Lang_13/src/main -o methods/Lang_13.txt
python3 count_methods.py /tmp/buggy_Lang_14/src/main -o methods/Lang_14.txt
python3 count_methods.py /tmp/buggy_Lang_15/src/main -o methods/Lang_15.txt
python3 count_methods.py /tmp/buggy_Lang_16/src/main -o methods/Lang_16.txt
python3 count_methods.py /tmp/buggy_Lang_17/src/main -o methods/Lang_17.txt
python3 count_methods.py /tmp/buggy_Lang_18/src/main -o methods/Lang_18.txt
python3 count_methods.py /tmp/buggy_Lang_19/src/main -o methods/Lang_19.txt
python3 count_methods.py /tmp/buggy_Lang_20/src/main -o methods/Lang_20.txt
python3 count_methods.py /tmp/buggy_Lang_21/src/main -o methods/Lang_21.txt
python3 count_methods.py /tmp/buggy_Lang_22/src/main -o methods/Lang_22.txt
python3 count_methods.py /tmp/buggy_Lang_23/src/main -o methods/Lang_23.txt
python3 count_methods.py /tmp/buggy_Lang_24/src/main -o methods/Lang_24.txt
python3 count_methods.py /tmp/buggy_Lang_25/src/main -o methods/Lang_25.txt
python3 count_methods.py /tmp/buggy_Lang_26/src/main -o methods/Lang_26.txt
python3 count_methods.py /tmp/buggy_Lang_27/src/main -o methods/Lang_27.txt
python3 count_methods.py /tmp/buggy_Lang_28/src/main -o methods/Lang_28.txt
python3 count_methods.py /tmp/buggy_Lang_29/src/main -o methods/Lang_29.txt
python3 count_methods.py /tmp/buggy_Lang_3/src/main -o methods/Lang_3.txt
python3 count_methods.py /tmp/buggy_Lang_30/src/main -o methods/Lang_30.txt
python3 count_methods.py /tmp/buggy_Lang_31/src/main -o methods/Lang_31.txt
python3 count_methods.py /tmp/buggy_Lang_32/src/main -o methods/Lang_32.txt
python3 count_methods.py /tmp/buggy_Lang_33/src/main -o methods/Lang_33.txt
python3 count_methods.py /tmp/buggy_Lang_34/src/main -o methods/Lang_34.txt
python3 count_methods.py /tmp/buggy_Lang_35/src/main -o methods/Lang_35.txt
python3 count_methods.py /tmp/buggy_Lang_36/src/main -o methods/Lang_36.txt
python3 count_methods.py /tmp/buggy_Lang_37/src/main -o methods/Lang_37.txt
python3 count_methods.py /tmp/buggy_Lang_38/src/main -o methods/Lang_38.txt
python3 count_methods.py /tmp/buggy_Lang_39/src/main -o methods/Lang_39.txt
python3 count_methods.py /tmp/buggy_Lang_4/src/main -o methods/Lang_4.txt
python3 count_methods.py /tmp/buggy_Lang_40/src/main -o methods/Lang_40.txt
python3 count_methods.py /tmp/buggy_Lang_41/src/main -o methods/Lang_41.txt
python3 count_methods.py /tmp/buggy_Lang_42/src/main -o methods/Lang_42.txt
python3 count_methods.py /tmp/buggy_Lang_43/src/main -o methods/Lang_43.txt
python3 count_methods.py /tmp/buggy_Lang_44/src/main -o methods/Lang_44.txt
python3 count_methods.py /tmp/buggy_Lang_45/src/main -o methods/Lang_45.txt
python3 count_methods.py /tmp/buggy_Lang_46/src/main -o methods/Lang_46.txt
python3 count_methods.py /tmp/buggy_Lang_47/src/main -o methods/Lang_47.txt
python3 count_methods.py /tmp/buggy_Lang_48/src/main -o methods/Lang_48.txt
python3 count_methods.py /tmp/buggy_Lang_49/src/java -o methods/Lang_49.txt
python3 count_methods.py /tmp/buggy_Lang_5/src/main -o methods/Lang_5.txt
python3 count_methods.py /tmp/buggy_Lang_50/src/java -o methods/Lang_50.txt
python3 count_methods.py /tmp/buggy_Lang_51/src/java -o methods/Lang_51.txt
python3 count_methods.py /tmp/buggy_Lang_52/src/java -o methods/Lang_52.txt
python3 count_methods.py /tmp/buggy_Lang_53/src/java -o methods/Lang_53.txt
python3 count_methods.py /tmp/buggy_Lang_54/src/java -o methods/Lang_54.txt
python3 count_methods.py /tmp/buggy_Lang_55/src/java -o methods/Lang_55.txt
python3 count_methods.py /tmp/buggy_Lang_56/src/java -o methods/Lang_56.txt
python3 count_methods.py /tmp/buggy_Lang_57/src/java -o methods/Lang_57.txt
python3 count_methods.py /tmp/buggy_Lang_58/src/java -o methods/Lang_58.txt
python3 count_methods.py /tmp/buggy_Lang_59/src/java -o methods/Lang_59.txt
python3 count_methods.py /tmp/buggy_Lang_6/src/main -o methods/Lang_6.txt
python3 count_methods.py /tmp/buggy_Lang_60/src/java -o methods/Lang_60.txt
python3 count_methods.py /tmp/buggy_Lang_61/src/java -o methods/Lang_61.txt
python3 count_methods.py /tmp/buggy_Lang_62/src/java -o methods/Lang_62.txt
python3 count_methods.py /tmp/buggy_Lang_63/src/java -o methods/Lang_63.txt
python3 count_methods.py /tmp/buggy_Lang_64/src/java -o methods/Lang_64.txt
python3 count_methods.py /tmp/buggy_Lang_65/src/java -o methods/Lang_65.txt
python3 count_methods.py /tmp/buggy_Lang_7/src/main -o methods/Lang_7.txt
python3 count_methods.py /tmp/buggy_Lang_8/src/main -o methods/Lang_8.txt
python3 count_methods.py /tmp/buggy_Lang_9/src/main -o methods/Lang_9.txt
python3 count_methods.py /tmp/buggy_Math_1/src/main -o methods/Math_1.txt
python3 count_methods.py /tmp/buggy_Math_10/src/main -o methods/Math_10.txt
python3 count_methods.py /tmp/buggy_Math_100/src/java -o methods/Math_100.txt
python3 count_methods.py /tmp/buggy_Math_101/src/java -o methods/Math_101.txt
python3 count_methods.py /tmp/buggy_Math_102/src/java -o methods/Math_102.txt
python3 count_methods.py /tmp/buggy_Math_103/src/java -o methods/Math_103.txt
python3 count_methods.py /tmp/buggy_Math_104/src/java -o methods/Math_104.txt
python3 count_methods.py /tmp/buggy_Math_105/src/java -o methods/Math_105.txt
python3 count_methods.py /tmp/buggy_Math_106/src/java -o methods/Math_106.txt
python3 count_methods.py /tmp/buggy_Math_11/src/main -o methods/Math_11.txt
python3 count_methods.py /tmp/buggy_Math_12/src/main -o methods/Math_12.txt
python3 count_methods.py /tmp/buggy_Math_13/src/main -o methods/Math_13.txt
python3 count_methods.py /tmp/buggy_Math_14/src/main -o methods/Math_14.txt
python3 count_methods.py /tmp/buggy_Math_15/src/main -o methods/Math_15.txt
python3 count_methods.py /tmp/buggy_Math_16/src/main -o methods/Math_16.txt
python3 count_methods.py /tmp/buggy_Math_17/src/main -o methods/Math_17.txt
python3 count_methods.py /tmp/buggy_Math_18/src/main -o methods/Math_18.txt
python3 count_methods.py /tmp/buggy_Math_19/src/main -o methods/Math_19.txt
python3 count_methods.py /tmp/buggy_Math_2/src/main -o methods/Math_2.txt
python3 count_methods.py /tmp/buggy_Math_20/src/main -o methods/Math_20.txt
python3 count_methods.py /tmp/buggy_Math_21/src/main -o methods/Math_21.txt
python3 count_methods.py /tmp/buggy_Math_22/src/main -o methods/Math_22.txt
python3 count_methods.py /tmp/buggy_Math_23/src/main -o methods/Math_23.txt
python3 count_methods.py /tmp/buggy_Math_24/src/main -o methods/Math_24.txt
python3 count_methods.py /tmp/buggy_Math_25/src/main -o methods/Math_25.txt
python3 count_methods.py /tmp/buggy_Math_26/src/main -o methods/Math_26.txt
python3 count_methods.py /tmp/buggy_Math_27/src/main -o methods/Math_27.txt
python3 count_methods.py /tmp/buggy_Math_28/src/main -o methods/Math_28.txt
python3 count_methods.py /tmp/buggy_Math_29/src/main -o methods/Math_29.txt
python3 count_methods.py /tmp/buggy_Math_3/src/main -o methods/Math_3.txt
python3 count_methods.py /tmp/buggy_Math_30/src/main -o methods/Math_30.txt
python3 count_methods.py /tmp/buggy_Math_31/src/main -o methods/Math_31.txt
python3 count_methods.py /tmp/buggy_Math_32/src/main -o methods/Math_32.txt
python3 count_methods.py /tmp/buggy_Math_33/src/main -o methods/Math_33.txt
python3 count_methods.py /tmp/buggy_Math_34/src/main -o methods/Math_34.txt
python3 count_methods.py /tmp/buggy_Math_35/src/main -o methods/Math_35.txt
python3 count_methods.py /tmp/buggy_Math_36/src/main -o methods/Math_36.txt
python3 count_methods.py /tmp/buggy_Math_37/src/main -o methods/Math_37.txt
python3 count_methods.py /tmp/buggy_Math_38/src/main -o methods/Math_38.txt
python3 count_methods.py /tmp/buggy_Math_39/src/main -o methods/Math_39.txt
python3 count_methods.py /tmp/buggy_Math_4/src/main -o methods/Math_4.txt
python3 count_methods.py /tmp/buggy_Math_40/src/main -o methods/Math_40.txt
python3 count_methods.py /tmp/buggy_Math_41/src/main -o methods/Math_41.txt
python3 count_methods.py /tmp/buggy_Math_42/src/main -o methods/Math_42.txt
python3 count_methods.py /tmp/buggy_Math_43/src/main -o methods/Math_43.txt
python3 count_methods.py /tmp/buggy_Math_44/src/main -o methods/Math_44.txt
python3 count_methods.py /tmp/buggy_Math_45/src/main -o methods/Math_45.txt
python3 count_methods.py /tmp/buggy_Math_46/src/main -o methods/Math_46.txt
python3 count_methods.py /tmp/buggy_Math_47/src/main -o methods/Math_47.txt
python3 count_methods.py /tmp/buggy_Math_48/src/main -o methods/Math_48.txt
python3 count_methods.py /tmp/buggy_Math_49/src/main -o methods/Math_49.txt
python3 count_methods.py /tmp/buggy_Math_5/src/main -o methods/Math_5.txt
python3 count_methods.py /tmp/buggy_Math_50/src/main -o methods/Math_50.txt
python3 count_methods.py /tmp/buggy_Math_51/src/main -o methods/Math_51.txt
python3 count_methods.py /tmp/buggy_Math_52/src/main -o methods/Math_52.txt
python3 count_methods.py /tmp/buggy_Math_53/src/main -o methods/Math_53.txt
python3 count_methods.py /tmp/buggy_Math_54/src/main -o methods/Math_54.txt
python3 count_methods.py /tmp/buggy_Math_55/src/main -o methods/Math_55.txt
python3 count_methods.py /tmp/buggy_Math_56/src/main -o methods/Math_56.txt
python3 count_methods.py /tmp/buggy_Math_57/src/main -o methods/Math_57.txt
python3 count_methods.py /tmp/buggy_Math_58/src/main -o methods/Math_58.txt
python3 count_methods.py /tmp/buggy_Math_59/src/main -o methods/Math_59.txt
python3 count_methods.py /tmp/buggy_Math_6/src/main -o methods/Math_6.txt
python3 count_methods.py /tmp/buggy_Math_60/src/main -o methods/Math_60.txt
python3 count_methods.py /tmp/buggy_Math_61/src/main -o methods/Math_61.txt
python3 count_methods.py /tmp/buggy_Math_62/src/main -o methods/Math_62.txt
python3 count_methods.py /tmp/buggy_Math_63/src/main -o methods/Math_63.txt
python3 count_methods.py /tmp/buggy_Math_64/src/main -o methods/Math_64.txt
python3 count_methods.py /tmp/buggy_Math_65/src/main -o methods/Math_65.txt
python3 count_methods.py /tmp/buggy_Math_66/src/main -o methods/Math_66.txt
python3 count_methods.py /tmp/buggy_Math_67/src/main -o methods/Math_67.txt
python3 count_methods.py /tmp/buggy_Math_68/src/main -o methods/Math_68.txt
python3 count_methods.py /tmp/buggy_Math_69/src/main -o methods/Math_69.txt
python3 count_methods.py /tmp/buggy_Math_7/src/main -o methods/Math_7.txt
python3 count_methods.py /tmp/buggy_Math_70/src/main -o methods/Math_70.txt
python3 count_methods.py /tmp/buggy_Math_71/src/main -o methods/Math_71.txt
python3 count_methods.py /tmp/buggy_Math_72/src/main -o methods/Math_72.txt
python3 count_methods.py /tmp/buggy_Math_73/src/main -o methods/Math_73.txt
python3 count_methods.py /tmp/buggy_Math_74/src/main -o methods/Math_74.txt
python3 count_methods.py /tmp/buggy_Math_75/src/main -o methods/Math_75.txt
python3 count_methods.py /tmp/buggy_Math_76/src/main -o methods/Math_76.txt
python3 count_methods.py /tmp/buggy_Math_77/src/main -o methods/Math_77.txt
python3 count_methods.py /tmp/buggy_Math_78/src/main -o methods/Math_78.txt
python3 count_methods.py /tmp/buggy_Math_79/src/main -o methods/Math_79.txt
python3 count_methods.py /tmp/buggy_Math_8/src/main -o methods/Math_8.txt
python3 count_methods.py /tmp/buggy_Math_80/src/main -o methods/Math_80.txt
python3 count_methods.py /tmp/buggy_Math_81/src/main -o methods/Math_81.txt
python3 count_methods.py /tmp/buggy_Math_82/src/main -o methods/Math_82.txt
python3 count_methods.py /tmp/buggy_Math_83/src/main -o methods/Math_83.txt
python3 count_methods.py /tmp/buggy_Math_84/src/main -o methods/Math_84.txt
python3 count_methods.py /tmp/buggy_Math_85/src/java -o methods/Math_85.txt
python3 count_methods.py /tmp/buggy_Math_86/src/java -o methods/Math_86.txt
python3 count_methods.py /tmp/buggy_Math_87/src/java -o methods/Math_87.txt
python3 count_methods.py /tmp/buggy_Math_88/src/java -o methods/Math_88.txt
python3 count_methods.py /tmp/buggy_Math_89/src/java -o methods/Math_89.txt
python3 count_methods.py /tmp/buggy_Math_9/src/main -o methods/Math_9.txt
python3 count_methods.py /tmp/buggy_Math_90/src/java -o methods/Math_90.txt
python3 count_methods.py /tmp/buggy_Math_91/src/java -o methods/Math_91.txt
python3 count_methods.py /tmp/buggy_Math_92/src/java -o methods/Math_92.txt
python3 count_methods.py /tmp/buggy_Math_93/src/java -o methods/Math_93.txt
python3 count_methods.py /tmp/buggy_Math_94/src/java -o methods/Math_94.txt
python3 count_methods.py /tmp/buggy_Math_95/src/java -o methods/Math_95.txt
python3 count_methods.py /tmp/buggy_Math_96/src/java -o methods/Math_96.txt
python3 count_methods.py /tmp/buggy_Math_97/src/java -o methods/Math_97.txt
python3 count_methods.py /tmp/buggy_Math_98/src/java -o methods/Math_98.txt
python3 count_methods.py /tmp/buggy_Math_99/src/java -o methods/Math_99.txt
python3 count_methods.py /tmp/buggy_Time_1/src/main -o methods/Time_1.txt
python3 count_methods.py /tmp/buggy_Time_10/src/main -o methods/Time_10.txt
python3 count_methods.py /tmp/buggy_Time_11/src/main -o methods/Time_11.txt
python3 count_methods.py /tmp/buggy_Time_12/src/main -o methods/Time_12.txt
python3 count_methods.py /tmp/buggy_Time_13/src/main -o methods/Time_13.txt
python3 count_methods.py /tmp/buggy_Time_14/src/main -o methods/Time_14.txt
python3 count_methods.py /tmp/buggy_Time_15/src/main -o methods/Time_15.txt
python3 count_methods.py /tmp/buggy_Time_16/src/main -o methods/Time_16.txt
python3 count_methods.py /tmp/buggy_Time_17/src/main -o methods/Time_17.txt
python3 count_methods.py /tmp/buggy_Time_18/src/main -o methods/Time_18.txt
python3 count_methods.py /tmp/buggy_Time_19/src/main -o methods/Time_19.txt
python3 count_methods.py /tmp/buggy_Time_2/src/main -o methods/Time_2.txt
python3 count_methods.py /tmp/buggy_Time_20/src/main -o methods/Time_20.txt
python3 count_methods.py /tmp/buggy_Time_22/src/main -o methods/Time_22.txt
python3 count_methods.py /tmp/buggy_Time_23/src/main -o methods/Time_23.txt
python3 count_methods.py /tmp/buggy_Time_24/src/main -o methods/Time_24.txt
python3 count_methods.py /tmp/buggy_Time_25/src/main -o methods/Time_25.txt
python3 count_methods.py /tmp/buggy_Time_26/src/main -o methods/Time_26.txt
python3 count_methods.py /tmp/buggy_Time_27/src/main -o methods/Time_27.txt
python3 count_methods.py /tmp/buggy_Time_3/src/main -o methods/Time_3.txt
python3 count_methods.py /tmp/buggy_Time_4/src/main -o methods/Time_4.txt
python3 count_methods.py /tmp/buggy_Time_5/src/main -o methods/Time_5.txt
python3 count_methods.py /tmp/buggy_Time_6/src/main -o methods/Time_6.txt
python3 count_methods.py /tmp/buggy_Time_7/src/main -o methods/Time_7.txt
python3 count_methods.py /tmp/buggy_Time_8/src/main -o methods/Time_8.txt
python3 count_methods.py /tmp/buggy_Time_9/src/main -o methods/Time_9.txt
