defects4j checkout -p Chart -v 1b /tmp/buggy_Chart_1
defects4j checkout -p Chart -v 10b /tmp/buggy_Chart_10
defects4j checkout -p Chart -v 11b /tmp/buggy_Chart_11
defects4j checkout -p Chart -v 12b /tmp/buggy_Chart_12
defects4j checkout -p Chart -v 13b /tmp/buggy_Chart_13
defects4j checkout -p Chart -v 14b /tmp/buggy_Chart_14
defects4j checkout -p Chart -v 15b /tmp/buggy_Chart_15
defects4j checkout -p Chart -v 16b /tmp/buggy_Chart_16
defects4j checkout -p Chart -v 17b /tmp/buggy_Chart_17
defects4j checkout -p Chart -v 18b /tmp/buggy_Chart_18
defects4j checkout -p Chart -v 19b /tmp/buggy_Chart_19
defects4j checkout -p Chart -v 2b /tmp/buggy_Chart_2
defects4j checkout -p Chart -v 20b /tmp/buggy_Chart_20
defects4j checkout -p Chart -v 21b /tmp/buggy_Chart_21
defects4j checkout -p Chart -v 22b /tmp/buggy_Chart_22
defects4j checkout -p Chart -v 23b /tmp/buggy_Chart_23
defects4j checkout -p Chart -v 24b /tmp/buggy_Chart_24
defects4j checkout -p Chart -v 25b /tmp/buggy_Chart_25
defects4j checkout -p Chart -v 26b /tmp/buggy_Chart_26
defects4j checkout -p Chart -v 3b /tmp/buggy_Chart_3
defects4j checkout -p Chart -v 4b /tmp/buggy_Chart_4
defects4j checkout -p Chart -v 5b /tmp/buggy_Chart_5
defects4j checkout -p Chart -v 6b /tmp/buggy_Chart_6
defects4j checkout -p Chart -v 7b /tmp/buggy_Chart_7
defects4j checkout -p Chart -v 8b /tmp/buggy_Chart_8
defects4j checkout -p Chart -v 9b /tmp/buggy_Chart_9
defects4j checkout -p Closure -v 1b /tmp/buggy_Closure_1
defects4j checkout -p Closure -v 10b /tmp/buggy_Closure_10
defects4j checkout -p Closure -v 100b /tmp/buggy_Closure_100
defects4j checkout -p Closure -v 101b /tmp/buggy_Closure_101
defects4j checkout -p Closure -v 102b /tmp/buggy_Closure_102
defects4j checkout -p Closure -v 103b /tmp/buggy_Closure_103
defects4j checkout -p Closure -v 104b /tmp/buggy_Closure_104
defects4j checkout -p Closure -v 105b /tmp/buggy_Closure_105
defects4j checkout -p Closure -v 106b /tmp/buggy_Closure_106
defects4j checkout -p Closure -v 107b /tmp/buggy_Closure_107
defects4j checkout -p Closure -v 108b /tmp/buggy_Closure_108
defects4j checkout -p Closure -v 109b /tmp/buggy_Closure_109
defects4j checkout -p Closure -v 11b /tmp/buggy_Closure_11
defects4j checkout -p Closure -v 110b /tmp/buggy_Closure_110
defects4j checkout -p Closure -v 111b /tmp/buggy_Closure_111
defects4j checkout -p Closure -v 112b /tmp/buggy_Closure_112
defects4j checkout -p Closure -v 113b /tmp/buggy_Closure_113
defects4j checkout -p Closure -v 114b /tmp/buggy_Closure_114
defects4j checkout -p Closure -v 115b /tmp/buggy_Closure_115
defects4j checkout -p Closure -v 116b /tmp/buggy_Closure_116
defects4j checkout -p Closure -v 117b /tmp/buggy_Closure_117
defects4j checkout -p Closure -v 118b /tmp/buggy_Closure_118
defects4j checkout -p Closure -v 119b /tmp/buggy_Closure_119
defects4j checkout -p Closure -v 12b /tmp/buggy_Closure_12
defects4j checkout -p Closure -v 120b /tmp/buggy_Closure_120
defects4j checkout -p Closure -v 121b /tmp/buggy_Closure_121
defects4j checkout -p Closure -v 122b /tmp/buggy_Closure_122
defects4j checkout -p Closure -v 123b /tmp/buggy_Closure_123
defects4j checkout -p Closure -v 124b /tmp/buggy_Closure_124
defects4j checkout -p Closure -v 125b /tmp/buggy_Closure_125
defects4j checkout -p Closure -v 126b /tmp/buggy_Closure_126
defects4j checkout -p Closure -v 127b /tmp/buggy_Closure_127
defects4j checkout -p Closure -v 128b /tmp/buggy_Closure_128
defects4j checkout -p Closure -v 129b /tmp/buggy_Closure_129
defects4j checkout -p Closure -v 13b /tmp/buggy_Closure_13
defects4j checkout -p Closure -v 130b /tmp/buggy_Closure_130
defects4j checkout -p Closure -v 131b /tmp/buggy_Closure_131
defects4j checkout -p Closure -v 132b /tmp/buggy_Closure_132
defects4j checkout -p Closure -v 133b /tmp/buggy_Closure_133
defects4j checkout -p Closure -v 14b /tmp/buggy_Closure_14
defects4j checkout -p Closure -v 15b /tmp/buggy_Closure_15
defects4j checkout -p Closure -v 16b /tmp/buggy_Closure_16
defects4j checkout -p Closure -v 17b /tmp/buggy_Closure_17
defects4j checkout -p Closure -v 18b /tmp/buggy_Closure_18
defects4j checkout -p Closure -v 19b /tmp/buggy_Closure_19
defects4j checkout -p Closure -v 2b /tmp/buggy_Closure_2
defects4j checkout -p Closure -v 20b /tmp/buggy_Closure_20
defects4j checkout -p Closure -v 21b /tmp/buggy_Closure_21
defects4j checkout -p Closure -v 22b /tmp/buggy_Closure_22
defects4j checkout -p Closure -v 23b /tmp/buggy_Closure_23
defects4j checkout -p Closure -v 24b /tmp/buggy_Closure_24
defects4j checkout -p Closure -v 25b /tmp/buggy_Closure_25
defects4j checkout -p Closure -v 26b /tmp/buggy_Closure_26
defects4j checkout -p Closure -v 27b /tmp/buggy_Closure_27
defects4j checkout -p Closure -v 28b /tmp/buggy_Closure_28
defects4j checkout -p Closure -v 29b /tmp/buggy_Closure_29
defects4j checkout -p Closure -v 3b /tmp/buggy_Closure_3
defects4j checkout -p Closure -v 30b /tmp/buggy_Closure_30
defects4j checkout -p Closure -v 31b /tmp/buggy_Closure_31
defects4j checkout -p Closure -v 32b /tmp/buggy_Closure_32
defects4j checkout -p Closure -v 33b /tmp/buggy_Closure_33
defects4j checkout -p Closure -v 34b /tmp/buggy_Closure_34
defects4j checkout -p Closure -v 35b /tmp/buggy_Closure_35
defects4j checkout -p Closure -v 36b /tmp/buggy_Closure_36
defects4j checkout -p Closure -v 37b /tmp/buggy_Closure_37
defects4j checkout -p Closure -v 38b /tmp/buggy_Closure_38
defects4j checkout -p Closure -v 39b /tmp/buggy_Closure_39
defects4j checkout -p Closure -v 4b /tmp/buggy_Closure_4
defects4j checkout -p Closure -v 40b /tmp/buggy_Closure_40
defects4j checkout -p Closure -v 41b /tmp/buggy_Closure_41
defects4j checkout -p Closure -v 42b /tmp/buggy_Closure_42
defects4j checkout -p Closure -v 43b /tmp/buggy_Closure_43
defects4j checkout -p Closure -v 44b /tmp/buggy_Closure_44
defects4j checkout -p Closure -v 45b /tmp/buggy_Closure_45
defects4j checkout -p Closure -v 46b /tmp/buggy_Closure_46
defects4j checkout -p Closure -v 47b /tmp/buggy_Closure_47
defects4j checkout -p Closure -v 48b /tmp/buggy_Closure_48
defects4j checkout -p Closure -v 49b /tmp/buggy_Closure_49
defects4j checkout -p Closure -v 5b /tmp/buggy_Closure_5
defects4j checkout -p Closure -v 50b /tmp/buggy_Closure_50
defects4j checkout -p Closure -v 51b /tmp/buggy_Closure_51
defects4j checkout -p Closure -v 52b /tmp/buggy_Closure_52
defects4j checkout -p Closure -v 53b /tmp/buggy_Closure_53
defects4j checkout -p Closure -v 54b /tmp/buggy_Closure_54
defects4j checkout -p Closure -v 55b /tmp/buggy_Closure_55
defects4j checkout -p Closure -v 56b /tmp/buggy_Closure_56
defects4j checkout -p Closure -v 57b /tmp/buggy_Closure_57
defects4j checkout -p Closure -v 58b /tmp/buggy_Closure_58
defects4j checkout -p Closure -v 59b /tmp/buggy_Closure_59
defects4j checkout -p Closure -v 6b /tmp/buggy_Closure_6
defects4j checkout -p Closure -v 60b /tmp/buggy_Closure_60
defects4j checkout -p Closure -v 61b /tmp/buggy_Closure_61
defects4j checkout -p Closure -v 62b /tmp/buggy_Closure_62
defects4j checkout -p Closure -v 64b /tmp/buggy_Closure_64
defects4j checkout -p Closure -v 65b /tmp/buggy_Closure_65
defects4j checkout -p Closure -v 66b /tmp/buggy_Closure_66
defects4j checkout -p Closure -v 67b /tmp/buggy_Closure_67
defects4j checkout -p Closure -v 68b /tmp/buggy_Closure_68
defects4j checkout -p Closure -v 69b /tmp/buggy_Closure_69
defects4j checkout -p Closure -v 7b /tmp/buggy_Closure_7
defects4j checkout -p Closure -v 70b /tmp/buggy_Closure_70
defects4j checkout -p Closure -v 71b /tmp/buggy_Closure_71
defects4j checkout -p Closure -v 72b /tmp/buggy_Closure_72
defects4j checkout -p Closure -v 73b /tmp/buggy_Closure_73
defects4j checkout -p Closure -v 74b /tmp/buggy_Closure_74
defects4j checkout -p Closure -v 75b /tmp/buggy_Closure_75
defects4j checkout -p Closure -v 76b /tmp/buggy_Closure_76
defects4j checkout -p Closure -v 77b /tmp/buggy_Closure_77
defects4j checkout -p Closure -v 78b /tmp/buggy_Closure_78
defects4j checkout -p Closure -v 79b /tmp/buggy_Closure_79
defects4j checkout -p Closure -v 8b /tmp/buggy_Closure_8
defects4j checkout -p Closure -v 80b /tmp/buggy_Closure_80
defects4j checkout -p Closure -v 81b /tmp/buggy_Closure_81
defects4j checkout -p Closure -v 82b /tmp/buggy_Closure_82
defects4j checkout -p Closure -v 83b /tmp/buggy_Closure_83
defects4j checkout -p Closure -v 84b /tmp/buggy_Closure_84
defects4j checkout -p Closure -v 85b /tmp/buggy_Closure_85
defects4j checkout -p Closure -v 86b /tmp/buggy_Closure_86
defects4j checkout -p Closure -v 87b /tmp/buggy_Closure_87
defects4j checkout -p Closure -v 88b /tmp/buggy_Closure_88
defects4j checkout -p Closure -v 89b /tmp/buggy_Closure_89
defects4j checkout -p Closure -v 9b /tmp/buggy_Closure_9
defects4j checkout -p Closure -v 90b /tmp/buggy_Closure_90
defects4j checkout -p Closure -v 91b /tmp/buggy_Closure_91
defects4j checkout -p Closure -v 92b /tmp/buggy_Closure_92
defects4j checkout -p Closure -v 94b /tmp/buggy_Closure_94
defects4j checkout -p Closure -v 95b /tmp/buggy_Closure_95
defects4j checkout -p Closure -v 96b /tmp/buggy_Closure_96
defects4j checkout -p Closure -v 97b /tmp/buggy_Closure_97
defects4j checkout -p Closure -v 98b /tmp/buggy_Closure_98
defects4j checkout -p Closure -v 99b /tmp/buggy_Closure_99
defects4j checkout -p Lang -v 1b /tmp/buggy_Lang_1
defects4j checkout -p Lang -v 10b /tmp/buggy_Lang_10
defects4j checkout -p Lang -v 11b /tmp/buggy_Lang_11
defects4j checkout -p Lang -v 12b /tmp/buggy_Lang_12
defects4j checkout -p Lang -v 13b /tmp/buggy_Lang_13
defects4j checkout -p Lang -v 14b /tmp/buggy_Lang_14
defects4j checkout -p Lang -v 15b /tmp/buggy_Lang_15
defects4j checkout -p Lang -v 16b /tmp/buggy_Lang_16
defects4j checkout -p Lang -v 17b /tmp/buggy_Lang_17
defects4j checkout -p Lang -v 18b /tmp/buggy_Lang_18
defects4j checkout -p Lang -v 19b /tmp/buggy_Lang_19
defects4j checkout -p Lang -v 20b /tmp/buggy_Lang_20
defects4j checkout -p Lang -v 21b /tmp/buggy_Lang_21
defects4j checkout -p Lang -v 22b /tmp/buggy_Lang_22
defects4j checkout -p Lang -v 23b /tmp/buggy_Lang_23
defects4j checkout -p Lang -v 24b /tmp/buggy_Lang_24
defects4j checkout -p Lang -v 25b /tmp/buggy_Lang_25
defects4j checkout -p Lang -v 26b /tmp/buggy_Lang_26
defects4j checkout -p Lang -v 27b /tmp/buggy_Lang_27
defects4j checkout -p Lang -v 28b /tmp/buggy_Lang_28
defects4j checkout -p Lang -v 29b /tmp/buggy_Lang_29
defects4j checkout -p Lang -v 3b /tmp/buggy_Lang_3
defects4j checkout -p Lang -v 30b /tmp/buggy_Lang_30
defects4j checkout -p Lang -v 31b /tmp/buggy_Lang_31
defects4j checkout -p Lang -v 32b /tmp/buggy_Lang_32
defects4j checkout -p Lang -v 33b /tmp/buggy_Lang_33
defects4j checkout -p Lang -v 34b /tmp/buggy_Lang_34
defects4j checkout -p Lang -v 35b /tmp/buggy_Lang_35
defects4j checkout -p Lang -v 36b /tmp/buggy_Lang_36
defects4j checkout -p Lang -v 37b /tmp/buggy_Lang_37
defects4j checkout -p Lang -v 38b /tmp/buggy_Lang_38
defects4j checkout -p Lang -v 39b /tmp/buggy_Lang_39
defects4j checkout -p Lang -v 4b /tmp/buggy_Lang_4
defects4j checkout -p Lang -v 40b /tmp/buggy_Lang_40
defects4j checkout -p Lang -v 41b /tmp/buggy_Lang_41
defects4j checkout -p Lang -v 42b /tmp/buggy_Lang_42
defects4j checkout -p Lang -v 43b /tmp/buggy_Lang_43
defects4j checkout -p Lang -v 44b /tmp/buggy_Lang_44
defects4j checkout -p Lang -v 45b /tmp/buggy_Lang_45
defects4j checkout -p Lang -v 46b /tmp/buggy_Lang_46
defects4j checkout -p Lang -v 47b /tmp/buggy_Lang_47
defects4j checkout -p Lang -v 48b /tmp/buggy_Lang_48
defects4j checkout -p Lang -v 49b /tmp/buggy_Lang_49
defects4j checkout -p Lang -v 5b /tmp/buggy_Lang_5
defects4j checkout -p Lang -v 50b /tmp/buggy_Lang_50
defects4j checkout -p Lang -v 51b /tmp/buggy_Lang_51
defects4j checkout -p Lang -v 52b /tmp/buggy_Lang_52
defects4j checkout -p Lang -v 53b /tmp/buggy_Lang_53
defects4j checkout -p Lang -v 54b /tmp/buggy_Lang_54
defects4j checkout -p Lang -v 55b /tmp/buggy_Lang_55
defects4j checkout -p Lang -v 56b /tmp/buggy_Lang_56
defects4j checkout -p Lang -v 57b /tmp/buggy_Lang_57
defects4j checkout -p Lang -v 58b /tmp/buggy_Lang_58
defects4j checkout -p Lang -v 59b /tmp/buggy_Lang_59
defects4j checkout -p Lang -v 6b /tmp/buggy_Lang_6
defects4j checkout -p Lang -v 60b /tmp/buggy_Lang_60
defects4j checkout -p Lang -v 61b /tmp/buggy_Lang_61
defects4j checkout -p Lang -v 62b /tmp/buggy_Lang_62
defects4j checkout -p Lang -v 63b /tmp/buggy_Lang_63
defects4j checkout -p Lang -v 64b /tmp/buggy_Lang_64
defects4j checkout -p Lang -v 65b /tmp/buggy_Lang_65
defects4j checkout -p Lang -v 7b /tmp/buggy_Lang_7
defects4j checkout -p Lang -v 8b /tmp/buggy_Lang_8
defects4j checkout -p Lang -v 9b /tmp/buggy_Lang_9
defects4j checkout -p Math -v 1b /tmp/buggy_Math_1
defects4j checkout -p Math -v 10b /tmp/buggy_Math_10
defects4j checkout -p Math -v 100b /tmp/buggy_Math_100
defects4j checkout -p Math -v 101b /tmp/buggy_Math_101
defects4j checkout -p Math -v 102b /tmp/buggy_Math_102
defects4j checkout -p Math -v 103b /tmp/buggy_Math_103
defects4j checkout -p Math -v 104b /tmp/buggy_Math_104
defects4j checkout -p Math -v 105b /tmp/buggy_Math_105
defects4j checkout -p Math -v 106b /tmp/buggy_Math_106
defects4j checkout -p Math -v 11b /tmp/buggy_Math_11
defects4j checkout -p Math -v 12b /tmp/buggy_Math_12
defects4j checkout -p Math -v 13b /tmp/buggy_Math_13
defects4j checkout -p Math -v 14b /tmp/buggy_Math_14
defects4j checkout -p Math -v 15b /tmp/buggy_Math_15
defects4j checkout -p Math -v 16b /tmp/buggy_Math_16
defects4j checkout -p Math -v 17b /tmp/buggy_Math_17
defects4j checkout -p Math -v 18b /tmp/buggy_Math_18
defects4j checkout -p Math -v 19b /tmp/buggy_Math_19
defects4j checkout -p Math -v 2b /tmp/buggy_Math_2
defects4j checkout -p Math -v 20b /tmp/buggy_Math_20
defects4j checkout -p Math -v 21b /tmp/buggy_Math_21
defects4j checkout -p Math -v 22b /tmp/buggy_Math_22
defects4j checkout -p Math -v 23b /tmp/buggy_Math_23
defects4j checkout -p Math -v 24b /tmp/buggy_Math_24
defects4j checkout -p Math -v 25b /tmp/buggy_Math_25
defects4j checkout -p Math -v 26b /tmp/buggy_Math_26
defects4j checkout -p Math -v 27b /tmp/buggy_Math_27
defects4j checkout -p Math -v 28b /tmp/buggy_Math_28
defects4j checkout -p Math -v 29b /tmp/buggy_Math_29
defects4j checkout -p Math -v 3b /tmp/buggy_Math_3
defects4j checkout -p Math -v 30b /tmp/buggy_Math_30
defects4j checkout -p Math -v 31b /tmp/buggy_Math_31
defects4j checkout -p Math -v 32b /tmp/buggy_Math_32
defects4j checkout -p Math -v 33b /tmp/buggy_Math_33
defects4j checkout -p Math -v 34b /tmp/buggy_Math_34
defects4j checkout -p Math -v 35b /tmp/buggy_Math_35
defects4j checkout -p Math -v 36b /tmp/buggy_Math_36
defects4j checkout -p Math -v 37b /tmp/buggy_Math_37
defects4j checkout -p Math -v 38b /tmp/buggy_Math_38
defects4j checkout -p Math -v 39b /tmp/buggy_Math_39
defects4j checkout -p Math -v 4b /tmp/buggy_Math_4
defects4j checkout -p Math -v 40b /tmp/buggy_Math_40
defects4j checkout -p Math -v 41b /tmp/buggy_Math_41
defects4j checkout -p Math -v 42b /tmp/buggy_Math_42
defects4j checkout -p Math -v 43b /tmp/buggy_Math_43
defects4j checkout -p Math -v 44b /tmp/buggy_Math_44
defects4j checkout -p Math -v 45b /tmp/buggy_Math_45
defects4j checkout -p Math -v 46b /tmp/buggy_Math_46
defects4j checkout -p Math -v 47b /tmp/buggy_Math_47
defects4j checkout -p Math -v 48b /tmp/buggy_Math_48
defects4j checkout -p Math -v 49b /tmp/buggy_Math_49
defects4j checkout -p Math -v 5b /tmp/buggy_Math_5
defects4j checkout -p Math -v 50b /tmp/buggy_Math_50
defects4j checkout -p Math -v 51b /tmp/buggy_Math_51
defects4j checkout -p Math -v 52b /tmp/buggy_Math_52
defects4j checkout -p Math -v 53b /tmp/buggy_Math_53
defects4j checkout -p Math -v 54b /tmp/buggy_Math_54
defects4j checkout -p Math -v 55b /tmp/buggy_Math_55
defects4j checkout -p Math -v 56b /tmp/buggy_Math_56
defects4j checkout -p Math -v 57b /tmp/buggy_Math_57
defects4j checkout -p Math -v 58b /tmp/buggy_Math_58
defects4j checkout -p Math -v 59b /tmp/buggy_Math_59
defects4j checkout -p Math -v 6b /tmp/buggy_Math_6
defects4j checkout -p Math -v 60b /tmp/buggy_Math_60
defects4j checkout -p Math -v 61b /tmp/buggy_Math_61
defects4j checkout -p Math -v 62b /tmp/buggy_Math_62
defects4j checkout -p Math -v 63b /tmp/buggy_Math_63
defects4j checkout -p Math -v 64b /tmp/buggy_Math_64
defects4j checkout -p Math -v 65b /tmp/buggy_Math_65
defects4j checkout -p Math -v 66b /tmp/buggy_Math_66
defects4j checkout -p Math -v 67b /tmp/buggy_Math_67
defects4j checkout -p Math -v 68b /tmp/buggy_Math_68
defects4j checkout -p Math -v 69b /tmp/buggy_Math_69
defects4j checkout -p Math -v 7b /tmp/buggy_Math_7
defects4j checkout -p Math -v 70b /tmp/buggy_Math_70
defects4j checkout -p Math -v 71b /tmp/buggy_Math_71
defects4j checkout -p Math -v 72b /tmp/buggy_Math_72
defects4j checkout -p Math -v 73b /tmp/buggy_Math_73
defects4j checkout -p Math -v 74b /tmp/buggy_Math_74
defects4j checkout -p Math -v 75b /tmp/buggy_Math_75
defects4j checkout -p Math -v 76b /tmp/buggy_Math_76
defects4j checkout -p Math -v 77b /tmp/buggy_Math_77
defects4j checkout -p Math -v 78b /tmp/buggy_Math_78
defects4j checkout -p Math -v 79b /tmp/buggy_Math_79
defects4j checkout -p Math -v 8b /tmp/buggy_Math_8
defects4j checkout -p Math -v 80b /tmp/buggy_Math_80
defects4j checkout -p Math -v 81b /tmp/buggy_Math_81
defects4j checkout -p Math -v 82b /tmp/buggy_Math_82
defects4j checkout -p Math -v 83b /tmp/buggy_Math_83
defects4j checkout -p Math -v 84b /tmp/buggy_Math_84
defects4j checkout -p Math -v 85b /tmp/buggy_Math_85
defects4j checkout -p Math -v 86b /tmp/buggy_Math_86
defects4j checkout -p Math -v 87b /tmp/buggy_Math_87
defects4j checkout -p Math -v 88b /tmp/buggy_Math_88
defects4j checkout -p Math -v 89b /tmp/buggy_Math_89
defects4j checkout -p Math -v 9b /tmp/buggy_Math_9
defects4j checkout -p Math -v 90b /tmp/buggy_Math_90
defects4j checkout -p Math -v 91b /tmp/buggy_Math_91
defects4j checkout -p Math -v 92b /tmp/buggy_Math_92
defects4j checkout -p Math -v 93b /tmp/buggy_Math_93
defects4j checkout -p Math -v 94b /tmp/buggy_Math_94
defects4j checkout -p Math -v 95b /tmp/buggy_Math_95
defects4j checkout -p Math -v 96b /tmp/buggy_Math_96
defects4j checkout -p Math -v 97b /tmp/buggy_Math_97
defects4j checkout -p Math -v 98b /tmp/buggy_Math_98
defects4j checkout -p Math -v 99b /tmp/buggy_Math_99
defects4j checkout -p Time -v 1b /tmp/buggy_Time_1
defects4j checkout -p Time -v 10b /tmp/buggy_Time_10
defects4j checkout -p Time -v 11b /tmp/buggy_Time_11
defects4j checkout -p Time -v 12b /tmp/buggy_Time_12
defects4j checkout -p Time -v 13b /tmp/buggy_Time_13
defects4j checkout -p Time -v 14b /tmp/buggy_Time_14
defects4j checkout -p Time -v 15b /tmp/buggy_Time_15
defects4j checkout -p Time -v 16b /tmp/buggy_Time_16
defects4j checkout -p Time -v 17b /tmp/buggy_Time_17
defects4j checkout -p Time -v 18b /tmp/buggy_Time_18
defects4j checkout -p Time -v 19b /tmp/buggy_Time_19
defects4j checkout -p Time -v 2b /tmp/buggy_Time_2
defects4j checkout -p Time -v 20b /tmp/buggy_Time_20
defects4j checkout -p Time -v 22b /tmp/buggy_Time_22
defects4j checkout -p Time -v 23b /tmp/buggy_Time_23
defects4j checkout -p Time -v 24b /tmp/buggy_Time_24
defects4j checkout -p Time -v 25b /tmp/buggy_Time_25
defects4j checkout -p Time -v 26b /tmp/buggy_Time_26
defects4j checkout -p Time -v 27b /tmp/buggy_Time_27
defects4j checkout -p Time -v 3b /tmp/buggy_Time_3
defects4j checkout -p Time -v 4b /tmp/buggy_Time_4
defects4j checkout -p Time -v 5b /tmp/buggy_Time_5
defects4j checkout -p Time -v 6b /tmp/buggy_Time_6
defects4j checkout -p Time -v 7b /tmp/buggy_Time_7
defects4j checkout -p Time -v 8b /tmp/buggy_Time_8
defects4j checkout -p Time -v 9b /tmp/buggy_Time_9
